apiVersion: v1
kind: Secret
metadata:
  name: cred
  namespace: demo
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJoYXJzaGFkNzc3Ny5qZnJvZy5pbyI6IHsKCQkJImF1dGgiOiAiYUdGeWMyaGhaSE5vWVdsck1UVTFRR2R0WVdsc0xtTnZiVHBJWVhKelFERXlNelE9IgoJCX0KCX0KfQ==
type: kubernetes.io/dockerconfigjson
